import { getDatabase } from "../lib/database.js";

const sql = getDatabase({ direct: true });

await sql`
  CREATE TABLE IF NOT EXISTS products (
    id integer PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    lead text NOT NULL DEFAULT '',
    image_path text NOT NULL,
    metal text NOT NULL DEFAULT '',
    stone text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'draft'
      CHECK (status IN ('draft', 'published', 'archived')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )
`;

await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS wordpress_id integer`;
await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS description text NOT NULL DEFAULT ''`;
await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS video_url text NOT NULL DEFAULT ''`;
await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS carats text NOT NULL DEFAULT ''`;
await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS clarity text NOT NULL DEFAULT ''`;
await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0`;
await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS source_payload jsonb NOT NULL DEFAULT '{}'::jsonb`;
await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS published_at timestamptz`;

await sql`ALTER TABLE products DROP CONSTRAINT IF EXISTS products_status_check`;
await sql`
  ALTER TABLE products
  ADD CONSTRAINT products_status_check
  CHECK (status IN ('draft', 'pending', 'published', 'archived'))
`;

await sql`
  CREATE UNIQUE INDEX IF NOT EXISTS products_wordpress_id_unique
  ON products (wordpress_id)
  WHERE wordpress_id IS NOT NULL
`;

await sql`
  CREATE INDEX IF NOT EXISTS products_status_index
  ON products (status)
`;

await sql`
  CREATE INDEX IF NOT EXISTS products_catalog_order_index
  ON products (status, sort_order, id)
`;

await sql`
  CREATE TABLE IF NOT EXISTS product_media (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    kind text NOT NULL CHECK (kind IN ('image', 'video')),
    source_url text NOT NULL,
    public_url text,
    alt_text text NOT NULL DEFAULT '',
    position integer NOT NULL DEFAULT 0,
    is_primary boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (product_id, kind, position)
  )
`;

await sql`
  CREATE INDEX IF NOT EXISTS product_media_product_order_index
  ON product_media (product_id, kind, position)
`;

await sql`
  CREATE TABLE IF NOT EXISTS gallery_items (
    id integer PRIMARY KEY,
    wordpress_id integer UNIQUE,
    name text NOT NULL,
    source_url text NOT NULL,
    public_url text,
    alt_text text NOT NULL DEFAULT '',
    position integer NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'published'
      CHECK (status IN ('draft', 'published', 'archived')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )
`;

await sql`
  CREATE INDEX IF NOT EXISTS gallery_items_catalog_order_index
  ON gallery_items (status, position, id)
`;

await sql`
  CREATE TABLE IF NOT EXISTS catalog_imports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source text NOT NULL,
    source_hash text NOT NULL,
    product_count integer NOT NULL,
    media_count integer NOT NULL,
    gallery_count integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )
`;

console.log("Catalog schema v2 is ready.");
