import ArrowIcon from '@/components/ArrowIcon';
import {notFound} from 'next/navigation';
import Link from 'next/link';
import {getProducts, getSiteContent} from '@/lib/collection';
import JewelGallery from '@/components/JewelGallery';
import ContactBand from '@/components/ContactBand';
export const dynamic = 'force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const products = await getProducts();return {title:products.find(p=>p.slug===slug)?.name||'Nie znaleziono projektu'}}
export default async function Product({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const [products, siteContent]=await Promise.all([getProducts(), getSiteContent()]);const p=products.find(p=>p.slug===slug);if(!p)return notFound();const facts=[['Metal',p.metal],['Kamień',p.stone],['Masa kamienia',p.carats],['Czystość kamienia',p.clarity]].filter(([,value])=>value);return <><div className="wrap"><nav className="breadcrumb" aria-label="Ścieżka nawigacji"><Link href="/katalog">Pierścionki</Link><span aria-hidden="true">/</span><span aria-current="page">{p.name}</span></nav><div className="product-layout"><JewelGallery images={p.images} name={p.name} video={p.video}/><div className="product-detail"><span className="eyebrow">Projekt pracowni Michała Nowaka</span><h1>{p.name}</h1><p className="lead">{p.lead||'Poznaj projekt naszej pracowni. Porozmawiajmy o jego detalach i możliwościach dopasowania do Ciebie.'}</p>{facts.length>0&&<dl className="facts">{facts.map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl>}<p style={{marginTop:25}}>Cena i termin ustalane indywidualnie.</p><div className="actions"><Link className="button" href={`/kontakt?projekt=${encodeURIComponent(p.name)}`}>Zapytaj o ten pierścionek <span aria-hidden="true"><ArrowIcon /></span></Link></div><p className="muted" style={{marginTop:20}}>Wolisz porozmawiać? <a className="text-link" href={`tel:${(siteContent.phone || '+48 501 321 347').replace(/[\s()-]/g, '')}`}>{siteContent.phone || '+48 501 321 347'}</a></p><details className="product-info" open><summary>Opis projektu</summary><p>{p.description||'Szczegóły materiałów i wykonania omówimy podczas rozmowy z pracownią.'}</p></details><details className="product-info"><summary>Indywidualna wersja</summary><p>Podoba Ci się ten projekt, ale myślisz o innym detalu? Opowiedz nam o swoich oczekiwaniach. Dobór kamieni, metalu i możliwości wykonania ustalimy wspólnie.</p></details></div></div></div><ContactBand/></>}
